ip: 0.0.0.0
httpPort: ${httpPort:9880}
enableHttp: true
enableHttp2: true
httpsPort: ${httpsPort:9443}
enableHttps: ${enableHttps:false}
ioThreads: ${ioThreads:1}
workerThreads: ${workerThreads:1}
alwaysSetDate: false
