
# Singleton service factory configuration/IoC injection
singletons:
  - com.networknt.handler.HandlerProvider:
    - com.xlongwei.logserver.PathHandlerProvider
  - com.networknt.handler.MiddlewareHandler:
#    - com.networknt.exception.ExceptionHandler
    - com.networknt.body.BodyHandler
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
    - com.xlongwei.logserver.FileIndexer
  # - com.networknt.server.Test2StartupHook
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.ShutdownHookProvider:
  # - com.networknt.server.Test1ShutdownHook

